# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-14177-e5-cse-322-16/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xcku3p-ffva676-3-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ip_top
    /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal
    /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/map
  } {
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_wtr.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ref.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_rd_wr.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_periodic.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_group.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ecc_merge_enc.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ecc_gen.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ecc_fi_xor.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ecc_dec_fix.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ecc_buf.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ecc.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_ctl.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_cmd_mux_c.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_cmd_mux_ap.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_arb_p.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_arb_mux_p.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_arb_c.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_arb_a.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_act_timer.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc_act_rank.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/controller/ddr4_v2_2_mc.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ui/ddr4_v2_2_ui_wr_data.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ui/ddr4_v2_2_ui_rd_data.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ui/ddr4_v2_2_ui_cmd.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ui/ddr4_v2_2_ui.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_ar_channel.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_aw_channel.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_b_channel.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_cmd_arbiter.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_cmd_fsm.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_cmd_translator.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_fifo.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_incr_cmd.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_r_channel.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_w_channel.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_wr_cmd_fsm.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_wrap_cmd.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_a_upsizer.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_register_slice.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axi_upsizer.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_axic_register_slice.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_carry_and.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_carry_latch_and.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_carry_latch_or.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_carry_or.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_command_fifo.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_comparator.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_comparator_sel.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_comparator_sel_static.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_r_upsizer.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi/ddr4_v2_2_w_upsizer.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_addr_decode.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_read.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg_bank.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_reg.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_top.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/axi_ctrl/ddr4_v2_2_axi_ctrl_write.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/clocking/ddr4_v2_2_infrastructure.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_xsdb_bram.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_write.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_wr_byte.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_wr_bit.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_sync.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_read.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_rd_en.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_pi.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_mc_odt.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_debug_microblaze.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_cplx_data.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_cplx.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_config_rom.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_addr_decode.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_top.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal_xsdb_arbiter.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_cal.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_chipscope_xsdb_slave.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_v2_2_dp_AB9.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ip_top/ddr4.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ip_top/ddr4_ddr4.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ip_top/ddr4_ddr4_mem_intfc.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal/ddr4_ddr4_cal_riu.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/phy/ddr4_phy_v2_2_xiphy.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/iob/ddr4_phy_v2_2_iob_byte.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/iob/ddr4_phy_v2_2_iob.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/clocking/ddr4_phy_v2_2_pll.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_tristate_wrapper.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_riuor_wrapper.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_control_wrapper.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_byte_wrapper.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/xiphy_files/ddr4_phy_v2_2_xiphy_bitslice_wrapper.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/phy/ddr4_phy_ddr4.sv
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/ip_top/ddr4_phy.sv
      /home/software/vivado-2018.3/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/ip_top
    /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/rtl/cal
    /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_1/rtl/map
  } {
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/ip_0/synth/ddr4_microblaze_mcs.v
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/synth/bd_c703.v
    }
      rt::read_vhdl -lib microblaze_v11_0_0 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_0/hdl/microblaze_v11_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_0/synth/bd_c703_microblaze_I_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_1/synth/bd_c703_rst_0_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_2/synth/bd_c703_ilmb_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_3/synth/bd_c703_dlmb_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_4/synth/bd_c703_dlmb_cntlr_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_5/synth/bd_c703_ilmb_cntlr_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_6/synth/bd_c703_lmb_bram_I_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_7/synth/bd_c703_second_dlmb_cntlr_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_8/synth/bd_c703_second_ilmb_cntlr_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_9/synth/bd_c703_second_lmb_bram_I_0.vhd
      /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_10/synth/bd_c703_iomodule_0_0.vhd
    }
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_1/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_1/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_v10_v3_0_9 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_2/hdl/lmb_v10_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib lmb_bram_if_cntlr_v4_0_15 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_4/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_2 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_6/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib iomodule_v3_1_4 /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2018.3/xc7vx690tffg1157-2/ddr4/bd_0/ip/ip_10/hdl/iomodule_v3_1_vh_rfs.vhd
      rt::read_vhdl -lib xpm /home/software/vivado-2018.3/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ddr4
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-14177-e5-cse-322-16/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
