# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2019.2/xcvu35p-fsvh2104-3-e/axi_crossbar/axi_crossbar.xci
# IP: The module: 'axi_crossbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2019.2/xcvu35p-fsvh2104-3-e/axi_crossbar/axi_crossbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2019.2/xcvu35p-fsvh2104-3-e/axi_crossbar/axi_crossbar.xci
# IP: The module: 'axi_crossbar' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdl/izo5011/IkennaWorkSpace/DDR4_perf/hardware/ip_viv2019.2/xcvu35p-fsvh2104-3-e/axi_crossbar/axi_crossbar_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
